<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { realPaperApi } from '../api'
const profile = ref<any>(null), error = ref(false)
async function load() { error.value = false; try { const res: any = await realPaperApi.paperProfile(); profile.value = res.data } catch { error.value = true } }
onMounted(load)
</script>
<template><section class="paper-history"><header><div><small>整卷能力档案</small><h2>看见每一套的进步</h2></div><router-link to="/history">全部练习 →</router-link></header><p v-if="error">整卷档案加载失败。<button @click="load">重新加载</button></p><p v-else-if="!profile">正在读取整卷档案…</p><template v-else><div class="history-scores"><router-link v-for="r in profile.recent.slice(-5)" :key="r.attemptId" :to="`/paper-report/${r.attemptId}`"><strong>{{ r.totalScore }}<small>/{{ r.maxScore }}</small></strong><span>{{ r.title }}</span><small>得分率 {{ r.scoreRate }}% · 查看整卷诊断 →</small></router-link></div><p v-if="!profile.count">完成一套新版申论批改后，将自动生成整卷诊断与能力档案。</p><div class="profile-tags"><span v-for="e in profile.errorTrends.slice(0, 5)" :key="e.tag">{{ e.tag }} ×{{ e.count }} · {{ e.trend }}</span></div><p class="note">{{ profile.note }}</p></template></section></template>
<style scoped>.paper-history{padding:26px;background:#fff;border:1px solid #e1e8f4;border-radius:18px;margin-bottom:24px}.paper-history header{display:flex;align-items:center;justify-content:space-between;gap:15px}.paper-history h2{font-size:22px;margin:5px 0 20px}.paper-history header small{color:#3265ed}.paper-history a{color:#3265ed;text-decoration:none;font-size:12px}.history-scores{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px}.history-scores a{background:#f5f8fe;border-radius:12px;padding:15px}.history-scores strong{font-size:29px}.history-scores strong small{font-size:12px;color:#8a99ae}.history-scores span{display:block;color:#60738f;font-size:12px;margin:8px 0}.profile-tags{display:flex;gap:10px;flex-wrap:wrap;margin-top:20px}.profile-tags span{font-size:12px;background:#f0f4fb;padding:6px 10px;border-radius:6px;color:#7086a7}.note{font-size:11px;color:#8a98ad;line-height:1.8;margin-bottom:0}</style>
